name: generating other formats

on:
  push:
    branches:
      - GA_converter_tmp
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: "3.9"

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install the required python packages
        run: python -m pip install .[test]

      - name: Other installations
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget curl

      - name: Generate other model representations
        run: |
          cd linkml-model
          for file in *.yaml; 
            do name=`basename ${file} .yaml`;  
            touch ../json-schema_autogen/${name}.json; 
          done
          if [ $? -eq 0 ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add json-schema_autogen/*.json
            git commit -m "generate"
            git push
          else
            echo "error"
          fi
